# Generated by Django 5.1.4 on 2025-02-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branches',
            new_name='Branch',
        ),
        migrations.RenameModel(
            old_name='Group',
            new_name='StudyGroup',
        ),
    ]
